database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:./target/accountsdb
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: update
    hibernate.show_sql: false

logging:
  level: WARN
  loggers:
    "de.ctdo": DEBUG
    "io": INFO
